(ns polymer.core-elements
  (:refer-clojure :exclude [list meta range]))

(defn- make-elem-ctor [tag]
  (fn [& args]
    (apply (.createElement js/document tag) args)))

(def a11y-keys           (make-elem-ctor "core-a11y-keys"))
(def ajax                (make-elem-ctor "core-ajax"))
(def animated-pages      (make-elem-ctor "core-animated-pages"))
(def animation           (make-elem-ctor "core-animation"))
(def collapse            (make-elem-ctor "core-collapse"))
(def component-page      (make-elem-ctor "core-component-page"))
(def docs                (make-elem-ctor "core-docs"))
(def doc-viewer          (make-elem-ctor "core-doc-viewer"))
(def drag-drop           (make-elem-ctor "core-drag-drop"))
(def drawer-panel        (make-elem-ctor "core-drawer-panel"))
(def dropdown            (make-elem-ctor "core-dropdown"))
(def dropdown-menu       (make-elem-ctor "core-dropdown-menu"))
(def elements            (make-elem-ctor "core-elements"))
(def field               (make-elem-ctor "core-field"))
(def focusable           (make-elem-ctor "core-focusable"))
(def header-panel        (make-elem-ctor "core-header-panel"))
(def icon                (make-elem-ctor "core-icon"))
(def icon-button         (make-elem-ctor "core-icon-button"))
(def icons               (make-elem-ctor "core-icons"))
(def iconset             (make-elem-ctor "core-iconset"))
(def iconset-svg         (make-elem-ctor "core-iconset-svg"))
(def image               (make-elem-ctor "core-image"))
(def input               (make-elem-ctor "core-input"))
(def item                (make-elem-ctor "core-item"))
(def label               (make-elem-ctor "core-label"))
(def layout-grid         (make-elem-ctor "core-layout-grid"))
(def layout-trbl         (make-elem-ctor "core-layout-trbl"))
(def list                (make-elem-ctor "core-list"))
(def localstorage        (make-elem-ctor "core-localstorage"))
(def media-query         (make-elem-ctor "core-media-query"))
(def menu                (make-elem-ctor "core-menu"))
(def menu-button         (make-elem-ctor "core-menu-button"))
(def meta                (make-elem-ctor "core-meta"))
(def overlay             (make-elem-ctor "core-overlay"))
(def pages               (make-elem-ctor "core-pages"))
(def range               (make-elem-ctor "core-range"))
(def scaffold            (make-elem-ctor "core-scaffold"))
(def scroll-header-panel (make-elem-ctor "core-scroll-header-panel"))
(def selection           (make-elem-ctor "core-selection"))
(def selector            (make-elem-ctor "core-selector"))
(def shared-lib          (make-elem-ctor "core-shared-lib"))
(def signals             (make-elem-ctor "core-signals"))
(def splitter            (make-elem-ctor "core-splitter"))
(def style               (make-elem-ctor "core-style"))
(def tests               (make-elem-ctor "core-tests"))
(def toolbar             (make-elem-ctor "core-toolbar"))
(def tooltip             (make-elem-ctor "core-tooltip"))
(def transition          (make-elem-ctor "core-transition"))
