(ns polymer.paper-elements)

(defn- make-elem-ctor [tag]
  (fn [& args]
    (apply (.createElement js/document tag) args)))

(def button-base         (make-elem-ctor "paper-button-base"))
(def button              (make-elem-ctor "paper-button"))
(def checkbox            (make-elem-ctor "paper-checkbox"))
(def action-dialog       (make-elem-ctor "paper-action-dialog"))
(def dialog-base         (make-elem-ctor "paper-dialog-base"))
(def dialog-transition   (make-elem-ctor "paper-dialog-transition"))
(def dialog              (make-elem-ctor "paper-dialog"))
(def dropdown-transition (make-elem-ctor "paper-dropdown-transition"))
(def dropdown            (make-elem-ctor "paper-dropdown"))
(def dropdown-menu       (make-elem-ctor "paper-dropdown-menu"))
(def fab                 (make-elem-ctor "paper-fab"))
(def focusable           (make-elem-ctor "paper-focusable"))
(def icon-button         (make-elem-ctor "paper-icon-button"))
(def autogrow-textarea   (make-elem-ctor "paper-autogrow-textarea"))
(def input-decorator     (make-elem-ctor "paper-input-decorator"))
(def input               (make-elem-ctor "paper-input"))
(def item                (make-elem-ctor "paper-item"))
(def menu-button         (make-elem-ctor "paper-menu-button"))
(def progress            (make-elem-ctor "paper-progress"))
(def radio-button        (make-elem-ctor "paper-radio-button"))
(def radio-group         (make-elem-ctor "paper-radio-group"))
(def ripple              (make-elem-ctor "paper-ripple"))
(def shadow              (make-elem-ctor "paper-shadow"))
(def slider              (make-elem-ctor "paper-slider"))
(def spinner             (make-elem-ctor "paper-spinner"))
(def tab                 (make-elem-ctor "paper-tab"))
(def tabs                (make-elem-ctor "paper-tabs"))
(def toast               (make-elem-ctor "paper-toast"))
(def toggle-button       (make-elem-ctor "paper-toggle-button"))
